### ISSUE TITLE
[Error] No FileSystem for scheme "jar"

### ISSUE THREAD

**Issue by nownikhil** [alexarchambault/ammonite-spark#118]
20/02/07 20:09:49 ERROR spark.SparkContext: Error initializing SparkContext.
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "jar"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3245)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3265)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:121)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3316)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3284)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:470)
	at org.apache.spark.deploy.yarn.Client.$anonfun$prepareLocalResources$19(Client.scala:534)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:529)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:873)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:178)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:57)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:178)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:503)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2523)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$5(SparkSession.scala:935)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
	at org.apache.spark.sql.ammonitesparkinternals.AmmoniteSparkSessionBuilder.getOrCreate(AmmoniteSparkSessionBuilder.scala:319)
	at org.apache.spark.sql.almondinternals.NotebookSparkSessionBuilder.getOrCreate(NotebookSparkSessionBuilder.scala:62)
      ...

I did logging and found that it was happening because it was trying to add jar with "jar:" prefix

jar:file:/var/lib/mesos/slaves/8589dac9-9426-4b19-a150-0729ca3e1843-S4883/frameworks/201104070004-0000002563-0000/executors/thermos-ngoyal-devel-pycx-notebook-0-52f7f7cb-22f9-44b1-9ff4-f0cff5b3932c/runs/770af79f-a40b-4ce4-bb64-7161fb2efb87/sandbox/.local/share/jupyter/kernels/scala/launcher.jar!/coursier/bootstrap/launcher/jars/scala-compiler-2.12.8.jar!/

I think this coming because of this line
https://github.com/alexarchambault/ammonite-spark/blob/master/modules/core/src/main/scala/org/apache/spark/sql/ammonitesparkinternals/AmmoniteSparkSessionBuilder.scala#L51

I first imported all the dependencies from spark-assembly/jars and then almond-spark in jupyter kernel.

**Comment by zoltanctoth** [comment]
@nownikhil have you resolved this already? I've been facing this issue for a while, but no luck so far.

**Comment by hygt** [comment]
I found a workaround, you can create an assembly of the almond-spark launcher with coursier:

```shell
cs bootstrap -i user -I user:sh.almond:scala-kernel-api_2.12.10:0.9.1 sh.almond:scala-kernel_2.12.10:0.9.1 -o /path/to/almond.jar --assembly --preamble=false
```

Then something like this to install it:

```shell
LAUNCHER=/path/to/almond.jar
CMD="java $JAVA_OPTS -jar $LAUNCHER"
exec $CMD --install --command "$CMD"
```
