### ISSUE TITLE
Spark stuck on my machine

### ISSUE THREAD

**Issue by lanking520** [alexarchambault/ammonite-spark#157]
I am trying to follow this instruction to use Spark on Jupyter Notebook: https://almond.sh/docs/usage-spark

However, I am not able to proceed even for the basic operation. I used JDK11 + Jupyter and Scala 2.12 installed on my Mac. I also installed the latest Almond Scala kernel.

reproducible code:
```
import $ivy.`org.apache.spark::spark-sql:2.4.0` // Or use any other 2.x version here
import $ivy.`sh.almond::almond-spark:0.10.9` 

import org.apache.spark.sql._

val spark = {
  NotebookSparkSession.builder()
    .master("local[*]")
    .getOrCreate()
}

def sc = spark.sparkContext
val rdd = sc.parallelize(1 to 100000000, 100)
val n = rdd.map(_ + 1).sum()
```

code failed at:
```
20/11/20 16:34:36 INFO Executor: Running task 8.0 in stage 0.0 (TID 8)
20/11/20 16:34:36 INFO Executor: Running task 3.0 in stage 0.0 (TID 3)
20/11/20 16:34:36 INFO Executor: Running task 6.0 in stage 0.0 (TID 6)
20/11/20 16:34:36 INFO Executor: Running task 4.0 in stage 0.0 (TID 4)
20/11/20 16:34:36 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
20/11/20 16:34:36 INFO Executor: Running task 7.0 in stage 0.0 (TID 7)
20/11/20 16:34:36 INFO Executor: Running task 2.0 in stage 0.0 (TID 2)
20/11/20 16:34:36 INFO Executor: Running task 10.0 in stage 0.0 (TID 10)
20/11/20 16:34:36 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
20/11/20 16:34:36 INFO Executor: Running task 11.0 in stage 0.0 (TID 11)
20/11/20 16:34:36 INFO Executor: Running task 5.0 in stage 0.0 (TID 5)
20/11/20 16:34:36 INFO Executor: Running task 9.0 in stage 0.0 (TID 9)
20/11/20 16:34:36 INFO Executor: Fetching spark://192.168.22.57:61510/jars/jupyter-api_2.12-0.10.9-sources.jar with timestamp 1605918875016
20/11/20 16:35:52 ERROR Utils: Aborting task
java.io.IOException: Failed to connect to /192.168.22.57:61510
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.downloadClient(NettyRpcEnv.scala:368)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$openChannel$4(NettyRpcEnv.scala:336)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.rpc.netty.NettyRpcEnv.openChannel(NettyRpcEnv.scala:335)
	at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:693)
	at org.apache.spark.util.Utils$.fetchFile(Utils.scala:509)
	at org.apache.spark.executor.Executor.$anonfun$updateDependencies$7(Executor.scala:806)
	at org.apache.spark.executor.Executor.$anonfun$updateDependencies$7$adapted(Executor.scala:797)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:797)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:369)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Operation timed out: /192.168.22.57:61510
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
Caused by: java.net.ConnectException: Operation timed out
	... 11 more
20/11/20 16:35:52 WARN Utils: Suppressing exception in catch: null
java.lang.NullPointerException
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1402)
	at org.apache.spark.rpc.netty.NettyRpcEnv.openChannel(NettyRpcEnv.scala:335)
	at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:693)
	at org.apache.spark.util.Utils$.fetchFile(Utils.scala:509)
	at org.apache.spark.executor.Executor.$anonfun$updateDependencies$7(Executor.scala:806)
	at org.apache.spark.executor.Executor.$anonfun$updateDependencies$7$adapted(Executor.scala:797)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:797)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:369)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
20/11/20 16:35:52 INFO Executor: Fetching spark://192.168.22.57:61510/jars/jupyter-api_2.12-0.10.9-sources.jar with timestamp 1605918875016
```

I think this issue is more on the jar I used. Switching to `AmoniteSparkSession` doesn't help either. I tested locally with a general Scala setup and it seemed worked fine.

**Comment by lanking520** [comment]
Spark 2.4.6 and Spark 3.0.0 did not work...

**Comment by lanking520** [comment]
log during the startup
```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/11/20 16:34:33 INFO SparkContext: Running Spark version 2.4.0
20/11/20 16:34:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/11/20 16:34:34 INFO SparkContext: Submitted application: 81253ac8-368f-4ad3-9dfd-8793693c9c17
20/11/20 16:34:34 INFO SecurityManager: Changing view acls to: qingla
20/11/20 16:34:34 INFO SecurityManager: Changing modify acls to: qingla
20/11/20 16:34:34 INFO SecurityManager: Changing view acls groups to: 
20/11/20 16:34:34 INFO SecurityManager: Changing modify acls groups to: 
20/11/20 16:34:34 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(qingla); groups with view permissions: Set(); users  with modify permissions: Set(qingla); groups with modify permissions: Set()
20/11/20 16:34:34 INFO Utils: Successfully started service 'sparkDriver' on port 61510.
20/11/20 16:34:34 INFO SparkEnv: Registering MapOutputTracker
20/11/20 16:34:34 INFO SparkEnv: Registering BlockManagerMaster
20/11/20 16:34:34 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/11/20 16:34:34 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/11/20 16:34:34 INFO DiskBlockManager: Created local directory at /private/var/folders/qy/41_sjvss273_xcdjd_y74rzmzrh5b6/T/blockmgr-2e089a12-1391-425b-9462-39a427e66044
20/11/20 16:34:34 INFO MemoryStore: MemoryStore started with capacity 2.2 GB
20/11/20 16:34:34 INFO SparkEnv: Registering OutputCommitCoordinator
20/11/20 16:34:34 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/11/20 16:34:34 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.22.57:4040
```
